# Generated by Django 3.2.7 on 2021-10-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='confirmpassword',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
