# Generated by Django 3.2.7 on 2021-11-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211105_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
